// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { CheckVerificationCodeData, CheckVerificationCodeErrors, CheckVerificationCodeResponses, GetClientData, GetClientErrors, GetClientResponses, GetGlobalConfigData, GetGlobalConfigErrors, GetGlobalConfigResponses, GetPrivacyPolicyData, GetPrivacyPolicyErrors, GetPrivacyPolicyResponses, GetStatData, GetStatErrors, GetStatResponses, GetTosData, GetTosErrors, GetTosResponses, HeartbeatData, HeartbeatErrors, HeartbeatResponses, SendEmailCodeData, SendEmailCodeErrors, SendEmailCodeResponses, SendSmsCodeData, SendSmsCodeErrors, SendSmsCodeResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Check verification code
 */
export const checkVerificationCode = <ThrowOnError extends boolean = false>(options: Options<CheckVerificationCodeData, ThrowOnError>) => (options.client ?? client).post<CheckVerificationCodeResponses, CheckVerificationCodeErrors, ThrowOnError>({
    url: '/check_verification_code',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Client
 */
export const getClient = <ThrowOnError extends boolean = false>(options?: Options<GetClientData, ThrowOnError>) => (options?.client ?? client).get<GetClientResponses, GetClientErrors, ThrowOnError>({ url: '/client', ...options });

/**
 * Heartbeat
 */
export const heartbeat = <ThrowOnError extends boolean = false>(options?: Options<HeartbeatData, ThrowOnError>) => (options?.client ?? client).get<HeartbeatResponses, HeartbeatErrors, ThrowOnError>({ url: '/heartbeat', ...options });

/**
 * Get verification code
 */
export const sendEmailCode = <ThrowOnError extends boolean = false>(options: Options<SendEmailCodeData, ThrowOnError>) => (options.client ?? client).post<SendEmailCodeResponses, SendEmailCodeErrors, ThrowOnError>({
    url: '/send_code',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get sms verification code
 */
export const sendSmsCode = <ThrowOnError extends boolean = false>(options: Options<SendSmsCodeData, ThrowOnError>) => (options.client ?? client).post<SendSmsCodeResponses, SendSmsCodeErrors, ThrowOnError>({
    url: '/send_sms_code',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get global config
 */
export const getGlobalConfig = <ThrowOnError extends boolean = false>(options?: Options<GetGlobalConfigData, ThrowOnError>) => (options?.client ?? client).get<GetGlobalConfigResponses, GetGlobalConfigErrors, ThrowOnError>({ url: '/site/config', ...options });

/**
 * Get Privacy Policy
 */
export const getPrivacyPolicy = <ThrowOnError extends boolean = false>(options?: Options<GetPrivacyPolicyData, ThrowOnError>) => (options?.client ?? client).get<GetPrivacyPolicyResponses, GetPrivacyPolicyErrors, ThrowOnError>({ url: '/site/privacy', ...options });

/**
 * Get stat
 */
export const getStat = <ThrowOnError extends boolean = false>(options?: Options<GetStatData, ThrowOnError>) => (options?.client ?? client).get<GetStatResponses, GetStatErrors, ThrowOnError>({ url: '/site/stat', ...options });

/**
 * Get Tos Content
 */
export const getTos = <ThrowOnError extends boolean = false>(options?: Options<GetTosData, ThrowOnError>) => (options?.client ?? client).get<GetTosResponses, GetTosErrors, ThrowOnError>({ url: '/site/tos', ...options });
