// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1/common` | (string & {});
};

export type AuthConfig = {
    device: DeviceAuthticateConfig;
    email: EmailAuthticateConfig;
    mobile: MobileAuthenticateConfig;
    register: PubilcRegisterConfig;
};

export type CheckVerificationCodeRequest = {
    account: string;
    code: string;
    method: string;
    type: number;
};

export type CheckVerificationCodeRespone = {
    status: boolean;
};

export type Currency = {
    currency_symbol: string;
    currency_unit: string;
};

export type DeviceAuthticateConfig = {
    enable: boolean;
    enable_security: boolean;
    only_real_device: boolean;
};

export type DownloadLink = {
    android?: string;
    harmony?: string;
    ios?: string;
    linux?: string;
    mac?: string;
    windows?: string;
};

export type EmailAuthticateConfig = {
    domain_suffix_list: string;
    enable: boolean;
    enable_domain_suffix: boolean;
    enable_verify: boolean;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type GetGlobalConfigResponse = {
    auth: AuthConfig;
    currency: Currency;
    invite: InviteConfig;
    oauth_methods: Array<string> | null;
    site: SiteConfig;
    subscribe: SubscribeConfig;
    verify: VeifyConfig;
    verify_code: PubilcVerifyCodeConfig;
    web_ad: boolean;
};

export type GetStatResponse = {
    country: number;
    node: number;
    protocol: Array<string> | null;
    user: number;
};

export type GetSubscribeClientResponse = {
    list: Array<SubscribeClient> | null;
    total: number;
};

export type GetTosResponse = {
    tos_content: string;
};

export type HeartbeatResponse = {
    message?: string;
    status: boolean;
    timestamp?: number;
};

export type InviteConfig = {
    forced_invite: boolean;
    only_first_purchase: boolean;
    referral_percentage: number;
};

export type MobileAuthenticateConfig = {
    enable: boolean;
    enable_whitelist: boolean;
    whitelist: Array<string> | null;
};

export type PrivacyPolicyConfig = {
    privacy_policy: string;
};

export type Problem = {
    code?: number;
    detail?: string;
    errors?: Array<ErrorDetail> | null;
    instance?: string;
    status?: number;
    title?: string;
    type?: string;
};

export type PubilcRegisterConfig = {
    enable_ip_register_limit: boolean;
    ip_register_limit: number;
    ip_register_limit_duration: number;
    stop_register: boolean;
};

export type PubilcVerifyCodeConfig = {
    verify_code_interval: number;
};

export type SendCodeRequest = {
    email: string;
    type: number;
};

export type SendCodeResponse = {
    code?: string;
    status: boolean;
};

export type SendSmsCodeRequest = {
    telephone: string;
    telephone_area_code: string;
    type: number;
};

export type SiteConfig = {
    custom_data: string;
    custom_html: string;
    host: string;
    keywords: string;
    site_desc: string;
    site_logo: string;
    site_name: string;
};

export type SubscribeClient = {
    description?: string;
    download_link?: DownloadLink;
    icon?: string;
    id: number;
    is_default: boolean;
    name: string;
    scheme?: string;
};

export type SubscribeConfig = {
    pan_domain: boolean;
    single_model: boolean;
    subscribe_domain: string;
    subscribe_path: string;
    user_agent_limit: boolean;
    user_agent_list: string;
};

export type VeifyConfig = {
    enable_login_verify: boolean;
    enable_register_verify: boolean;
    enable_reset_password_verify: boolean;
    turnstile_site_key: string;
};

export type CheckVerificationCodeData = {
    body: CheckVerificationCodeRequest;
    path?: never;
    query?: never;
    url: '/check_verification_code';
};

export type CheckVerificationCodeErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Too Many Requests
     */
    429: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Bad Gateway
     */
    502: Problem;
};

export type CheckVerificationCodeError = CheckVerificationCodeErrors[keyof CheckVerificationCodeErrors];

export type CheckVerificationCodeResponses = {
    /**
     * OK
     */
    200: CheckVerificationCodeRespone;
};

export type CheckVerificationCodeResponse = CheckVerificationCodeResponses[keyof CheckVerificationCodeResponses];

export type GetClientData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/client';
};

export type GetClientErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Too Many Requests
     */
    429: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Bad Gateway
     */
    502: Problem;
};

export type GetClientError = GetClientErrors[keyof GetClientErrors];

export type GetClientResponses = {
    /**
     * OK
     */
    200: GetSubscribeClientResponse;
};

export type GetClientResponse = GetClientResponses[keyof GetClientResponses];

export type HeartbeatData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/heartbeat';
};

export type HeartbeatErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Too Many Requests
     */
    429: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Bad Gateway
     */
    502: Problem;
};

export type HeartbeatError = HeartbeatErrors[keyof HeartbeatErrors];

export type HeartbeatResponses = {
    /**
     * OK
     */
    200: HeartbeatResponse;
};

export type HeartbeatResponse2 = HeartbeatResponses[keyof HeartbeatResponses];

export type SendEmailCodeData = {
    body: SendCodeRequest;
    path?: never;
    query?: never;
    url: '/send_code';
};

export type SendEmailCodeErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Too Many Requests
     */
    429: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Bad Gateway
     */
    502: Problem;
};

export type SendEmailCodeError = SendEmailCodeErrors[keyof SendEmailCodeErrors];

export type SendEmailCodeResponses = {
    /**
     * OK
     */
    200: SendCodeResponse;
};

export type SendEmailCodeResponse = SendEmailCodeResponses[keyof SendEmailCodeResponses];

export type SendSmsCodeData = {
    body: SendSmsCodeRequest;
    path?: never;
    query?: never;
    url: '/send_sms_code';
};

export type SendSmsCodeErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Too Many Requests
     */
    429: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Bad Gateway
     */
    502: Problem;
};

export type SendSmsCodeError = SendSmsCodeErrors[keyof SendSmsCodeErrors];

export type SendSmsCodeResponses = {
    /**
     * OK
     */
    200: SendCodeResponse;
};

export type SendSmsCodeResponse = SendSmsCodeResponses[keyof SendSmsCodeResponses];

export type GetGlobalConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/site/config';
};

export type GetGlobalConfigErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Too Many Requests
     */
    429: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Bad Gateway
     */
    502: Problem;
};

export type GetGlobalConfigError = GetGlobalConfigErrors[keyof GetGlobalConfigErrors];

export type GetGlobalConfigResponses = {
    /**
     * OK
     */
    200: GetGlobalConfigResponse;
};

export type GetGlobalConfigResponse2 = GetGlobalConfigResponses[keyof GetGlobalConfigResponses];

export type GetPrivacyPolicyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/site/privacy';
};

export type GetPrivacyPolicyErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Too Many Requests
     */
    429: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Bad Gateway
     */
    502: Problem;
};

export type GetPrivacyPolicyError = GetPrivacyPolicyErrors[keyof GetPrivacyPolicyErrors];

export type GetPrivacyPolicyResponses = {
    /**
     * OK
     */
    200: PrivacyPolicyConfig;
};

export type GetPrivacyPolicyResponse = GetPrivacyPolicyResponses[keyof GetPrivacyPolicyResponses];

export type GetStatData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/site/stat';
};

export type GetStatErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Too Many Requests
     */
    429: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Bad Gateway
     */
    502: Problem;
};

export type GetStatError = GetStatErrors[keyof GetStatErrors];

export type GetStatResponses = {
    /**
     * OK
     */
    200: GetStatResponse;
};

export type GetStatResponse2 = GetStatResponses[keyof GetStatResponses];

export type GetTosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/site/tos';
};

export type GetTosErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Too Many Requests
     */
    429: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Bad Gateway
     */
    502: Problem;
};

export type GetTosError = GetTosErrors[keyof GetTosErrors];

export type GetTosResponses = {
    /**
     * OK
     */
    200: GetTosResponse;
};

export type GetTosResponse2 = GetTosResponses[keyof GetTosResponses];
