// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Announcement = {
    content: string;
    created_at: number;
    id: number;
    pinned: boolean | null;
    popup: boolean | null;
    show: boolean | null;
    title: string;
    updated_at: number;
};

export type BalanceLog = {
    amount: number;
    balance: number;
    order_no?: string;
    timestamp: number;
    type: number;
    user_id: number;
};

export type BindOAuthCallbackRequest = {
    callback: unknown;
    method: string;
};

export type BindOAuthRequest = {
    method: string;
    redirect: string;
};

export type BindOAuthResponse = {
    redirect: string;
};

export type BindTelegramResponse = {
    expired_at: number;
    url: string;
};

export type CheckUserResponse = {
    exist: boolean;
};

export type CheckoutOrderRequest = {
    orderNo: string;
    returnUrl?: string;
};

export type CheckoutOrderResponse = {
    checkout_url?: string;
    stripe?: StripePayment;
    type: string;
};

export type CloseOrderRequest = {
    orderNo: string;
};

export type CommissionLog = {
    amount: number;
    order_no: string;
    timestamp: number;
    type: number;
    user_id: number;
};

export type CommissionWithdrawRequest = {
    amount: number;
    content: string;
};

export type CreateUserTicketFollowRequest = {
    content: string;
    from: string;
    ticket_id: number;
    type: number;
};

export type CreateUserTicketRequest = {
    description: string;
    title: string;
};

export type DeviceLoginRequest = {
    IP: string;
    cf_token: string;
    identifier: string;
    user_agent: string;
};

export type Document = {
    content: string;
    created_at: number;
    id: number;
    show: boolean;
    tags: Array<string> | null;
    title: string;
    updated_at: number;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type Follow = {
    content: string;
    created_at: number;
    from: string;
    id: number;
    ticket_id: number;
    type: number;
};

export type GetAvailablePaymentMethodsResponse = {
    list: Array<PaymentMethod> | null;
};

export type GetDeviceListResponse = {
    list: Array<UserDevice> | null;
    total: number;
};

export type GetLoginLogResponse = {
    list: Array<UserLoginLog> | null;
    total: number;
};

export type GetOAuthMethodsResponse = {
    methods: Array<UserAuthMethod> | null;
};

export type GetSubscribeLogResponse = {
    list: Array<UserSubscribeLog> | null;
    total: number;
};

export type GetSubscriptionResponse = {
    list: Array<Subscribe> | null;
};

export type GetUserTicketListRequest = {
    page: number;
    search?: string;
    size: number;
    status?: number;
};

export type GetUserTicketListResponse = {
    list: Array<Ticket> | null;
    total: number;
};

export type LoginResponse = {
    token: string;
};

export type OAthLoginRequest = {
    method: string;
    redirect: string;
};

export type OAuthLoginGetTokenRequest = {
    callback: unknown;
    method: string;
};

export type OAuthLoginResponse = {
    redirect: string;
};

export type OrderDetail = {
    amount: number;
    commission?: number;
    coupon: string;
    coupon_discount: number;
    created_at: number;
    discount: number;
    fee_amount: number;
    gift_amount: number;
    id: number;
    method: string;
    order_no: string;
    payment: PaymentMethod;
    price: number;
    quantity: number;
    status: number;
    subscribe: Subscribe;
    subscribe_id: number;
    trade_no: string;
    type: number;
    updated_at: number;
    user_id: number;
};

export type PaymentMethod = {
    description: string;
    fee_amount: number;
    fee_mode: number;
    fee_percent: number;
    icon: string;
    id: number;
    name: string;
    platform: string;
};

export type PortalPurchaseRequest = {
    auth_type: string;
    coupon?: string;
    identifier: string;
    invite_code?: string;
    password?: string;
    payment: number;
    quantity: number;
    subscribe_id: number;
    turnstile_token?: string;
};

export type PortalPurchaseResponse = {
    order_no: string;
};

export type PreOrderResponse = {
    amount: number;
    coupon: string;
    coupon_discount: number;
    discount: number;
    fee_amount: number;
    gift_amount: number;
    price: number;
};

export type PrePurchaseOrderRequest = {
    coupon?: string;
    payment?: number;
    quantity: number;
    subscribe_id: number;
};

export type PrePurchaseOrderResponse = {
    amount: number;
    coupon: string;
    coupon_discount: number;
    discount: number;
    fee_amount: number;
    price: number;
};

export type PreUnsubscribeRequest = {
    id: number;
};

export type PreUnsubscribeResponse = {
    deduction_amount: number;
};

export type PurchaseOrderRequest = {
    coupon?: string;
    payment?: number;
    quantity: number;
    subscribe_id: number;
};

export type PurchaseOrderResponse = {
    order_no: string;
};

export type QueryAnnouncementRequest = {
    page: number;
    pinned: boolean | null;
    popup: boolean | null;
    size: number;
};

export type QueryAnnouncementResponse = {
    announcements: Array<Announcement> | null;
    total: number;
};

export type QueryDocumentListResponse = {
    list: Array<Document> | null;
    total: number;
};

export type QueryOrderListResponse = {
    list: Array<OrderDetail> | null;
    total: number;
};

export type QueryPurchaseOrderResponse = {
    amount: number;
    coupon: string;
    coupon_discount: number;
    created_at: number;
    discount: number;
    fee_amount: number;
    order_no: string;
    payment: PaymentMethod;
    price: number;
    quantity: number;
    status: number;
    subscribe: Subscribe;
    token?: string;
};

export type QuerySubscribeListResponse = {
    list: Array<Subscribe> | null;
    total: number;
};

export type QueryUserAffiliateCountResponse = {
    registers: number;
    total_commission: number;
};

export type QueryUserAffiliateListResponse = {
    list: Array<UserAffiliate> | null;
    total: number;
};

export type QueryUserBalanceLogListResponse = {
    list: Array<BalanceLog> | null;
    total: number;
};

export type QueryUserCommissionLogListResponse = {
    list: Array<CommissionLog> | null;
    total: number;
};

export type QueryUserSubscribeListResponse = {
    list: Array<UserSubscribe> | null;
    total: number;
};

export type QueryUserSubscribeNodeListResponse = {
    list: Array<UserSubscribeInfo> | null;
};

export type QueryWithdrawalLogListResponse = {
    list: Array<WithdrawalLog> | null;
    total: number;
};

export type RechargeOrderRequest = {
    amount: number;
    payment: number;
};

export type RechargeOrderResponse = {
    order_no: string;
};

export type RenewalOrderRequest = {
    coupon?: string;
    payment: number;
    quantity: number;
    user_subscribe_id: number;
};

export type RenewalOrderResponse = {
    order_no: string;
};

export type ResetPasswordRequest = {
    IP: string;
    LoginType: string;
    UserAgent: string;
    cf_token: string;
    code: string;
    email: string;
    identifier: string;
    password: string;
};

export type ResetTrafficOrderRequest = {
    payment: number;
    user_subscribe_id: number;
};

export type ResetTrafficOrderResponse = {
    order_no: string;
};

export type ResetUserSubscribeTokenRequest = {
    user_subscribe_id: number;
};

export type StripePayment = {
    client_secret: string;
    method: string;
    publishable_key: string;
};

export type Subscribe = {
    allow_deduction: boolean;
    created_at: number;
    deduction_ratio: number;
    description: string;
    device_limit: number;
    discount: Array<SubscribeDiscount> | null;
    id: number;
    inventory: number;
    language: string;
    name: string;
    node_tags: Array<string> | null;
    nodes: Array<number> | null;
    quota: number;
    renewal_reset: boolean;
    replacement: number;
    reset_cycle: number;
    sell: boolean;
    show: boolean;
    show_original_price: boolean;
    sort: number;
    speed_limit: number;
    traffic: number;
    unit_price: number;
    unit_time: string;
    updated_at: number;
};

export type SubscribeDiscount = {
    discount: number;
    quantity: number;
};

export type TelephoneCheckUserResponse = {
    exist: boolean;
};

export type TelephoneLoginRequest = {
    IP: string;
    LoginType: string;
    UserAgent: string;
    cf_token: string;
    identifier: string;
    password: string;
    telephone: string;
    telephone_area_code: string;
    telephone_code: string;
};

export type TelephoneRegisterRequest = {
    IP: string;
    LoginType: string;
    UserAgent: string;
    cf_token: string;
    code: string;
    identifier: string;
    invite: string;
    password: string;
    telephone: string;
    telephone_area_code: string;
};

export type TelephoneResetPasswordRequest = {
    IP: string;
    LoginType: string;
    UserAgent: string;
    cf_token: string;
    code: string;
    identifier: string;
    password: string;
    telephone: string;
    telephone_area_code: string;
};

export type Ticket = {
    created_at: number;
    description: string;
    follow?: Array<Follow> | null;
    id: number;
    status: number;
    title: string;
    updated_at: number;
    user_id: number;
};

export type UnbindDeviceRequest = {
    id: number;
};

export type UnbindOAuthRequest = {
    method: string;
};

export type UnsubscribeRequest = {
    id: number;
};

export type UpdateBindEmailRequest = {
    email: string;
};

export type UpdateBindMobileRequest = {
    area_code: string;
    code: string;
    mobile: string;
};

export type UpdateUserNotifyRequest = {
    enable_balance_notify: boolean | null;
    enable_login_notify: boolean | null;
    enable_subscribe_notify: boolean | null;
    enable_trade_notify: boolean | null;
};

export type UpdateUserPasswordRequest = {
    password: string;
};

export type UpdateUserRulesRequest = {
    rules: Array<string> | null;
};

export type UpdateUserSubscribeNoteRequest = {
    note: string;
    user_subscribe_id: number;
};

export type UpdateUserTicketStatusRequest = {
    id: number;
    status: number | null;
};

export type User = {
    auth_methods: Array<UserAuthMethod> | null;
    avatar: string;
    balance: number;
    commission: number;
    created_at: number;
    deleted_at?: number;
    enable: boolean;
    enable_balance_notify: boolean;
    enable_login_notify: boolean;
    enable_subscribe_notify: boolean;
    enable_trade_notify: boolean;
    gift_amount: number;
    id: number;
    is_admin?: boolean;
    only_first_purchase: boolean;
    refer_code: string;
    referer_id: number;
    referral_percentage: number;
    rules: Array<string> | null;
    telegram: number;
    updated_at: number;
    user_devices: Array<UserDevice> | null;
};

export type UserAffiliate = {
    avatar: string;
    enable: boolean;
    identifier: string;
    registered_at: number;
};

export type UserAuthMethod = {
    auth_identifier: string;
    auth_type: string;
    verified: boolean;
};

export type UserDevice = {
    created_at: number;
    enabled: boolean;
    id: number;
    identifier: string;
    ip: string;
    online: boolean;
    updated_at: number;
    user_agent: string;
};

export type UserLoginLog = {
    id: number;
    login_ip: string;
    success: boolean;
    timestamp: number;
    user_agent: string;
    user_id: number;
};

export type UserLoginRequest = {
    IP: string;
    LoginType: string;
    UserAgent: string;
    cf_token: string;
    email: string;
    identifier: string;
    password: string;
};

export type UserRegisterRequest = {
    IP: string;
    LoginType: string;
    UserAgent: string;
    cf_token: string;
    code: string;
    email: string;
    identifier: string;
    invite: string;
    password: string;
};

export type UserSubscribe = {
    created_at: number;
    download: number;
    expire_time: number;
    finished_at: number;
    id: number;
    order_id: number;
    reset_time: number;
    short: string;
    start_time: number;
    status: number;
    subscribe: Subscribe;
    subscribe_id: number;
    token: string;
    traffic: number;
    updated_at: number;
    upload: number;
    user_id: number;
};

export type UserSubscribeInfo = {
    created_at: number;
    download: number;
    expire_time: number;
    finished_at: number;
    id: number;
    is_try_out: boolean;
    nodes: Array<UserSubscribeNodeInfo> | null;
    order_id: number;
    reset_time: number;
    start_time: number;
    status: number;
    subscribe_id: number;
    token: string;
    traffic: number;
    updated_at: number;
    upload: number;
    user_id: number;
};

export type UserSubscribeLog = {
    id: number;
    ip: string;
    timestamp: number;
    token: string;
    user_agent: string;
    user_id: number;
    user_subscribe_id: number;
};

export type UserSubscribeNodeInfo = {
    address: string;
    city: string;
    country: string;
    created_at: number;
    id: number;
    name: string;
    port: number;
    protocol: string;
    tags: Array<string> | null;
    uuid: string;
};

export type VerifyEmailRequest = {
    code: string;
    email: string;
};

export type WithdrawalLog = {
    amount: number;
    content: string;
    created_at: number;
    id: number;
    reason?: string;
    status: number;
    updated_at: number;
    user_id: number;
};

export type CheckUserData = {
    body?: never;
    path?: never;
    query?: {
        email?: string;
    };
    url: '/v1/auth/check';
};

export type CheckUserErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CheckUserError = CheckUserErrors[keyof CheckUserErrors];

export type CheckUserResponses = {
    /**
     * OK
     */
    200: CheckUserResponse;
};

export type CheckUserResponse2 = CheckUserResponses[keyof CheckUserResponses];

export type CheckUserTelephoneData = {
    body?: never;
    path?: never;
    query?: {
        telephone?: string;
    };
    url: '/v1/auth/check/telephone';
};

export type CheckUserTelephoneErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CheckUserTelephoneError = CheckUserTelephoneErrors[keyof CheckUserTelephoneErrors];

export type CheckUserTelephoneResponses = {
    /**
     * OK
     */
    200: TelephoneCheckUserResponse;
};

export type CheckUserTelephoneResponse = CheckUserTelephoneResponses[keyof CheckUserTelephoneResponses];

export type UserLoginData = {
    body: UserLoginRequest;
    headers?: {
        /**
         * Client IP from proxy
         */
        'X-Original-Forwarded-For'?: string;
        /**
         * User agent string
         */
        'User-Agent'?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/auth/login';
};

export type UserLoginErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UserLoginError = UserLoginErrors[keyof UserLoginErrors];

export type UserLoginResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type UserLoginResponse = UserLoginResponses[keyof UserLoginResponses];

export type DeviceLoginData = {
    body: DeviceLoginRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/login/device';
};

export type DeviceLoginErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeviceLoginError = DeviceLoginErrors[keyof DeviceLoginErrors];

export type DeviceLoginResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type DeviceLoginResponse = DeviceLoginResponses[keyof DeviceLoginResponses];

export type TelephoneLoginData = {
    body: TelephoneLoginRequest;
    headers?: {
        /**
         * Client IP from proxy
         */
        'X-Original-Forwarded-For'?: string;
        /**
         * User agent string
         */
        'User-Agent'?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/auth/login/telephone';
};

export type TelephoneLoginErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type TelephoneLoginError = TelephoneLoginErrors[keyof TelephoneLoginErrors];

export type TelephoneLoginResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type TelephoneLoginResponse = TelephoneLoginResponses[keyof TelephoneLoginResponses];

export type OAuthLoginData = {
    body: OAthLoginRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/oauth/login';
};

export type OAuthLoginErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OAuthLoginError = OAuthLoginErrors[keyof OAuthLoginErrors];

export type OAuthLoginResponses = {
    /**
     * OK
     */
    200: OAuthLoginResponse;
};

export type OAuthLoginResponse2 = OAuthLoginResponses[keyof OAuthLoginResponses];

export type OAuthLoginGetTokenData = {
    body: OAuthLoginGetTokenRequest;
    headers?: {
        /**
         * Client IP from proxy
         */
        'X-Original-Forwarded-For'?: string;
        /**
         * User agent string
         */
        'User-Agent'?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/auth/oauth/login/token';
};

export type OAuthLoginGetTokenErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OAuthLoginGetTokenError = OAuthLoginGetTokenErrors[keyof OAuthLoginGetTokenErrors];

export type OAuthLoginGetTokenResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type OAuthLoginGetTokenResponse = OAuthLoginGetTokenResponses[keyof OAuthLoginGetTokenResponses];

export type UserRegisterData = {
    body: UserRegisterRequest;
    headers?: {
        /**
         * Client IP from proxy
         */
        'X-Original-Forwarded-For'?: string;
        /**
         * User agent string
         */
        'User-Agent'?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/auth/register';
};

export type UserRegisterErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UserRegisterError = UserRegisterErrors[keyof UserRegisterErrors];

export type UserRegisterResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type UserRegisterResponse = UserRegisterResponses[keyof UserRegisterResponses];

export type TelephoneUserRegisterData = {
    body: TelephoneRegisterRequest;
    headers?: {
        /**
         * Client IP from proxy
         */
        'X-Original-Forwarded-For'?: string;
        /**
         * User agent string
         */
        'User-Agent'?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/auth/register/telephone';
};

export type TelephoneUserRegisterErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type TelephoneUserRegisterError = TelephoneUserRegisterErrors[keyof TelephoneUserRegisterErrors];

export type TelephoneUserRegisterResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type TelephoneUserRegisterResponse = TelephoneUserRegisterResponses[keyof TelephoneUserRegisterResponses];

export type ResetPasswordData = {
    body: ResetPasswordRequest;
    headers?: {
        /**
         * Client IP from proxy
         */
        'X-Original-Forwarded-For'?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/auth/reset';
};

export type ResetPasswordErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ResetPasswordError = ResetPasswordErrors[keyof ResetPasswordErrors];

export type ResetPasswordResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type ResetPasswordResponse = ResetPasswordResponses[keyof ResetPasswordResponses];

export type TelephoneResetPasswordData = {
    body: TelephoneResetPasswordRequest;
    headers?: {
        /**
         * Client IP from proxy
         */
        'X-Original-Forwarded-For'?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/auth/reset/telephone';
};

export type TelephoneResetPasswordErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type TelephoneResetPasswordError = TelephoneResetPasswordErrors[keyof TelephoneResetPasswordErrors];

export type TelephoneResetPasswordResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type TelephoneResetPasswordResponse = TelephoneResetPasswordResponses[keyof TelephoneResetPasswordResponses];

export type QueryAnnouncementData = {
    body: QueryAnnouncementRequest;
    path?: never;
    query?: never;
    url: '/v1/public/announcement/list';
};

export type QueryAnnouncementErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type QueryAnnouncementError = QueryAnnouncementErrors[keyof QueryAnnouncementErrors];

export type QueryAnnouncementResponses = {
    /**
     * OK
     */
    200: QueryAnnouncementResponse;
};

export type QueryAnnouncementResponse2 = QueryAnnouncementResponses[keyof QueryAnnouncementResponses];

export type QueryDocumentDetailData = {
    body?: never;
    path?: never;
    query?: {
        id?: number;
    };
    url: '/v1/public/document/detail';
};

export type QueryDocumentDetailErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type QueryDocumentDetailError = QueryDocumentDetailErrors[keyof QueryDocumentDetailErrors];

export type QueryDocumentDetailResponses = {
    /**
     * OK
     */
    200: Document;
};

export type QueryDocumentDetailResponse = QueryDocumentDetailResponses[keyof QueryDocumentDetailResponses];

export type QueryDocumentListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/public/document/list';
};

export type QueryDocumentListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type QueryDocumentListError = QueryDocumentListErrors[keyof QueryDocumentListErrors];

export type QueryDocumentListResponses = {
    /**
     * OK
     */
    200: QueryDocumentListResponse;
};

export type QueryDocumentListResponse2 = QueryDocumentListResponses[keyof QueryDocumentListResponses];

export type CloseOrderData = {
    body: CloseOrderRequest;
    path?: never;
    query?: never;
    url: '/v1/public/order/close';
};

export type CloseOrderErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CloseOrderError = CloseOrderErrors[keyof CloseOrderErrors];

export type CloseOrderResponses = {
    /**
     * No Content
     */
    204: void;
};

export type CloseOrderResponse = CloseOrderResponses[keyof CloseOrderResponses];

export type QueryOrderDetailData = {
    body?: never;
    path?: never;
    query?: {
        order_no?: string;
    };
    url: '/v1/public/order/detail';
};

export type QueryOrderDetailErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type QueryOrderDetailError = QueryOrderDetailErrors[keyof QueryOrderDetailErrors];

export type QueryOrderDetailResponses = {
    /**
     * OK
     */
    200: OrderDetail;
};

export type QueryOrderDetailResponse = QueryOrderDetailResponses[keyof QueryOrderDetailResponses];

export type QueryOrderListData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
    };
    url: '/v1/public/order/list';
};

export type QueryOrderListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type QueryOrderListError = QueryOrderListErrors[keyof QueryOrderListErrors];

export type QueryOrderListResponses = {
    /**
     * OK
     */
    200: QueryOrderListResponse;
};

export type QueryOrderListResponse2 = QueryOrderListResponses[keyof QueryOrderListResponses];

export type PreCreateOrderData = {
    body: PurchaseOrderRequest;
    path?: never;
    query?: never;
    url: '/v1/public/order/pre';
};

export type PreCreateOrderErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PreCreateOrderError = PreCreateOrderErrors[keyof PreCreateOrderErrors];

export type PreCreateOrderResponses = {
    /**
     * OK
     */
    200: PreOrderResponse;
};

export type PreCreateOrderResponse = PreCreateOrderResponses[keyof PreCreateOrderResponses];

export type PurchaseData = {
    body: PurchaseOrderRequest;
    path?: never;
    query?: never;
    url: '/v1/public/order/purchase';
};

export type PurchaseErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PurchaseError = PurchaseErrors[keyof PurchaseErrors];

export type PurchaseResponses = {
    /**
     * OK
     */
    200: PurchaseOrderResponse;
};

export type PurchaseResponse = PurchaseResponses[keyof PurchaseResponses];

export type RechargeData = {
    body: RechargeOrderRequest;
    path?: never;
    query?: never;
    url: '/v1/public/order/recharge';
};

export type RechargeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RechargeError = RechargeErrors[keyof RechargeErrors];

export type RechargeResponses = {
    /**
     * OK
     */
    200: RechargeOrderResponse;
};

export type RechargeResponse = RechargeResponses[keyof RechargeResponses];

export type RenewalData = {
    body: RenewalOrderRequest;
    path?: never;
    query?: never;
    url: '/v1/public/order/renewal';
};

export type RenewalErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RenewalError = RenewalErrors[keyof RenewalErrors];

export type RenewalResponses = {
    /**
     * OK
     */
    200: RenewalOrderResponse;
};

export type RenewalResponse = RenewalResponses[keyof RenewalResponses];

export type ResetTrafficData = {
    body: ResetTrafficOrderRequest;
    path?: never;
    query?: never;
    url: '/v1/public/order/reset';
};

export type ResetTrafficErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ResetTrafficError = ResetTrafficErrors[keyof ResetTrafficErrors];

export type ResetTrafficResponses = {
    /**
     * OK
     */
    200: ResetTrafficOrderResponse;
};

export type ResetTrafficResponse = ResetTrafficResponses[keyof ResetTrafficResponses];

export type GetAvailablePaymentMethodsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/public/payment/methods';
};

export type GetAvailablePaymentMethodsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetAvailablePaymentMethodsError = GetAvailablePaymentMethodsErrors[keyof GetAvailablePaymentMethodsErrors];

export type GetAvailablePaymentMethodsResponses = {
    /**
     * OK
     */
    200: GetAvailablePaymentMethodsResponse;
};

export type GetAvailablePaymentMethodsResponse2 = GetAvailablePaymentMethodsResponses[keyof GetAvailablePaymentMethodsResponses];

export type PurchaseCheckoutData = {
    body: CheckoutOrderRequest;
    path?: never;
    query?: never;
    url: '/v1/public/portal/order/checkout';
};

export type PurchaseCheckoutErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PurchaseCheckoutError = PurchaseCheckoutErrors[keyof PurchaseCheckoutErrors];

export type PurchaseCheckoutResponses = {
    /**
     * OK
     */
    200: CheckoutOrderResponse;
};

export type PurchaseCheckoutResponse = PurchaseCheckoutResponses[keyof PurchaseCheckoutResponses];

export type QueryPurchaseOrderData = {
    body?: never;
    path?: never;
    query?: {
        auth_type?: string;
        identifier?: string;
        order_no?: string;
    };
    url: '/v1/public/portal/order/status';
};

export type QueryPurchaseOrderErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type QueryPurchaseOrderError = QueryPurchaseOrderErrors[keyof QueryPurchaseOrderErrors];

export type QueryPurchaseOrderResponses = {
    /**
     * OK
     */
    200: QueryPurchaseOrderResponse;
};

export type QueryPurchaseOrderResponse2 = QueryPurchaseOrderResponses[keyof QueryPurchaseOrderResponses];

export type PortalGetAvailablePaymentMethodsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/public/portal/payment-method';
};

export type PortalGetAvailablePaymentMethodsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PortalGetAvailablePaymentMethodsError = PortalGetAvailablePaymentMethodsErrors[keyof PortalGetAvailablePaymentMethodsErrors];

export type PortalGetAvailablePaymentMethodsResponses = {
    /**
     * OK
     */
    200: GetAvailablePaymentMethodsResponse;
};

export type PortalGetAvailablePaymentMethodsResponse = PortalGetAvailablePaymentMethodsResponses[keyof PortalGetAvailablePaymentMethodsResponses];

export type PrePurchaseOrderData = {
    body: PrePurchaseOrderRequest;
    path?: never;
    query?: never;
    url: '/v1/public/portal/pre';
};

export type PrePurchaseOrderErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PrePurchaseOrderError = PrePurchaseOrderErrors[keyof PrePurchaseOrderErrors];

export type PrePurchaseOrderResponses = {
    /**
     * OK
     */
    200: PrePurchaseOrderResponse;
};

export type PrePurchaseOrderResponse2 = PrePurchaseOrderResponses[keyof PrePurchaseOrderResponses];

export type PortalPurchaseData = {
    body: PortalPurchaseRequest;
    path?: never;
    query?: never;
    url: '/v1/public/portal/purchase';
};

export type PortalPurchaseErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PortalPurchaseError = PortalPurchaseErrors[keyof PortalPurchaseErrors];

export type PortalPurchaseResponses = {
    /**
     * OK
     */
    200: PortalPurchaseResponse;
};

export type PortalPurchaseResponse2 = PortalPurchaseResponses[keyof PortalPurchaseResponses];

export type GetSubscriptionData = {
    body?: never;
    path?: never;
    query?: {
        language?: string;
    };
    url: '/v1/public/portal/subscribe';
};

export type GetSubscriptionErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetSubscriptionError = GetSubscriptionErrors[keyof GetSubscriptionErrors];

export type GetSubscriptionResponses = {
    /**
     * OK
     */
    200: GetSubscriptionResponse;
};

export type GetSubscriptionResponse2 = GetSubscriptionResponses[keyof GetSubscriptionResponses];

export type QuerySubscribeListData = {
    body?: never;
    path?: never;
    query?: {
        language?: string;
    };
    url: '/v1/public/subscribe/list';
};

export type QuerySubscribeListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type QuerySubscribeListError = QuerySubscribeListErrors[keyof QuerySubscribeListErrors];

export type QuerySubscribeListResponses = {
    /**
     * OK
     */
    200: QuerySubscribeListResponse;
};

export type QuerySubscribeListResponse2 = QuerySubscribeListResponses[keyof QuerySubscribeListResponses];

export type QueryUserSubscribeNodeListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/public/subscribe/node/list';
};

export type QueryUserSubscribeNodeListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type QueryUserSubscribeNodeListError = QueryUserSubscribeNodeListErrors[keyof QueryUserSubscribeNodeListErrors];

export type QueryUserSubscribeNodeListResponses = {
    /**
     * OK
     */
    200: QueryUserSubscribeNodeListResponse;
};

export type QueryUserSubscribeNodeListResponse2 = QueryUserSubscribeNodeListResponses[keyof QueryUserSubscribeNodeListResponses];

export type GetUserTicketDetailsData = {
    body?: never;
    path?: never;
    query?: {
        id?: number;
    };
    url: '/v1/public/ticket/detail';
};

export type GetUserTicketDetailsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetUserTicketDetailsError = GetUserTicketDetailsErrors[keyof GetUserTicketDetailsErrors];

export type GetUserTicketDetailsResponses = {
    /**
     * OK
     */
    200: Ticket;
};

export type GetUserTicketDetailsResponse = GetUserTicketDetailsResponses[keyof GetUserTicketDetailsResponses];

export type CreateUserTicketFollowData = {
    body: CreateUserTicketFollowRequest;
    path?: never;
    query?: never;
    url: '/v1/public/ticket/follow';
};

export type CreateUserTicketFollowErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateUserTicketFollowError = CreateUserTicketFollowErrors[keyof CreateUserTicketFollowErrors];

export type CreateUserTicketFollowResponses = {
    /**
     * No Content
     */
    204: void;
};

export type CreateUserTicketFollowResponse = CreateUserTicketFollowResponses[keyof CreateUserTicketFollowResponses];

export type GetUserTicketListData = {
    body: GetUserTicketListRequest;
    path?: never;
    query?: never;
    url: '/v1/public/ticket/list';
};

export type GetUserTicketListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetUserTicketListError = GetUserTicketListErrors[keyof GetUserTicketListErrors];

export type GetUserTicketListResponses = {
    /**
     * OK
     */
    200: GetUserTicketListResponse;
};

export type GetUserTicketListResponse2 = GetUserTicketListResponses[keyof GetUserTicketListResponses];

export type CreateUserTicketData = {
    body: CreateUserTicketRequest;
    path?: never;
    query?: never;
    url: '/v1/public/ticket/ticket';
};

export type CreateUserTicketErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateUserTicketError = CreateUserTicketErrors[keyof CreateUserTicketErrors];

export type CreateUserTicketResponses = {
    /**
     * No Content
     */
    204: void;
};

export type CreateUserTicketResponse = CreateUserTicketResponses[keyof CreateUserTicketResponses];

export type UpdateUserTicketStatusData = {
    body: UpdateUserTicketStatusRequest;
    path?: never;
    query?: never;
    url: '/v1/public/ticket/ticket';
};

export type UpdateUserTicketStatusErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateUserTicketStatusError = UpdateUserTicketStatusErrors[keyof UpdateUserTicketStatusErrors];

export type UpdateUserTicketStatusResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UpdateUserTicketStatusResponse = UpdateUserTicketStatusResponses[keyof UpdateUserTicketStatusResponses];

export type QueryUserAffiliateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/public/user/affiliate/count';
};

export type QueryUserAffiliateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type QueryUserAffiliateError = QueryUserAffiliateErrors[keyof QueryUserAffiliateErrors];

export type QueryUserAffiliateResponses = {
    /**
     * OK
     */
    200: QueryUserAffiliateCountResponse;
};

export type QueryUserAffiliateResponse = QueryUserAffiliateResponses[keyof QueryUserAffiliateResponses];

export type QueryUserAffiliateListData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
    };
    url: '/v1/public/user/affiliate/list';
};

export type QueryUserAffiliateListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type QueryUserAffiliateListError = QueryUserAffiliateListErrors[keyof QueryUserAffiliateListErrors];

export type QueryUserAffiliateListResponses = {
    /**
     * OK
     */
    200: QueryUserAffiliateListResponse;
};

export type QueryUserAffiliateListResponse2 = QueryUserAffiliateListResponses[keyof QueryUserAffiliateListResponses];

export type QueryUserBalanceLogData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/public/user/balance_log';
};

export type QueryUserBalanceLogErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type QueryUserBalanceLogError = QueryUserBalanceLogErrors[keyof QueryUserBalanceLogErrors];

export type QueryUserBalanceLogResponses = {
    /**
     * OK
     */
    200: QueryUserBalanceLogListResponse;
};

export type QueryUserBalanceLogResponse = QueryUserBalanceLogResponses[keyof QueryUserBalanceLogResponses];

export type UpdateBindEmailData = {
    body: UpdateBindEmailRequest;
    path?: never;
    query?: never;
    url: '/v1/public/user/bind_email';
};

export type UpdateBindEmailErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateBindEmailError = UpdateBindEmailErrors[keyof UpdateBindEmailErrors];

export type UpdateBindEmailResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UpdateBindEmailResponse = UpdateBindEmailResponses[keyof UpdateBindEmailResponses];

export type UpdateBindMobileData = {
    body: UpdateBindMobileRequest;
    path?: never;
    query?: never;
    url: '/v1/public/user/bind_mobile';
};

export type UpdateBindMobileErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateBindMobileError = UpdateBindMobileErrors[keyof UpdateBindMobileErrors];

export type UpdateBindMobileResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UpdateBindMobileResponse = UpdateBindMobileResponses[keyof UpdateBindMobileResponses];

export type BindOAuthData = {
    body: BindOAuthRequest;
    path?: never;
    query?: never;
    url: '/v1/public/user/bind_oauth';
};

export type BindOAuthErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type BindOAuthError = BindOAuthErrors[keyof BindOAuthErrors];

export type BindOAuthResponses = {
    /**
     * OK
     */
    200: BindOAuthResponse;
};

export type BindOAuthResponse2 = BindOAuthResponses[keyof BindOAuthResponses];

export type BindOAuthCallbackData = {
    body: BindOAuthCallbackRequest;
    path?: never;
    query?: never;
    url: '/v1/public/user/bind_oauth/callback';
};

export type BindOAuthCallbackErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type BindOAuthCallbackError = BindOAuthCallbackErrors[keyof BindOAuthCallbackErrors];

export type BindOAuthCallbackResponses = {
    /**
     * No Content
     */
    204: void;
};

export type BindOAuthCallbackResponse = BindOAuthCallbackResponses[keyof BindOAuthCallbackResponses];

export type BindTelegramData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/public/user/bind_telegram';
};

export type BindTelegramErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type BindTelegramError = BindTelegramErrors[keyof BindTelegramErrors];

export type BindTelegramResponses = {
    /**
     * OK
     */
    200: BindTelegramResponse;
};

export type BindTelegramResponse2 = BindTelegramResponses[keyof BindTelegramResponses];

export type QueryUserCommissionLogData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
    };
    url: '/v1/public/user/commission_log';
};

export type QueryUserCommissionLogErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type QueryUserCommissionLogError = QueryUserCommissionLogErrors[keyof QueryUserCommissionLogErrors];

export type QueryUserCommissionLogResponses = {
    /**
     * OK
     */
    200: QueryUserCommissionLogListResponse;
};

export type QueryUserCommissionLogResponse = QueryUserCommissionLogResponses[keyof QueryUserCommissionLogResponses];

export type CommissionWithdrawData = {
    body: CommissionWithdrawRequest;
    path?: never;
    query?: never;
    url: '/v1/public/user/commission_withdraw';
};

export type CommissionWithdrawErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CommissionWithdrawError = CommissionWithdrawErrors[keyof CommissionWithdrawErrors];

export type CommissionWithdrawResponses = {
    /**
     * OK
     */
    200: WithdrawalLog;
};

export type CommissionWithdrawResponse = CommissionWithdrawResponses[keyof CommissionWithdrawResponses];

export type GetDeviceListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/public/user/devices';
};

export type GetDeviceListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetDeviceListError = GetDeviceListErrors[keyof GetDeviceListErrors];

export type GetDeviceListResponses = {
    /**
     * OK
     */
    200: GetDeviceListResponse;
};

export type GetDeviceListResponse2 = GetDeviceListResponses[keyof GetDeviceListResponses];

export type QueryUserInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/public/user/info';
};

export type QueryUserInfoErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type QueryUserInfoError = QueryUserInfoErrors[keyof QueryUserInfoErrors];

export type QueryUserInfoResponses = {
    /**
     * OK
     */
    200: User;
};

export type QueryUserInfoResponse = QueryUserInfoResponses[keyof QueryUserInfoResponses];

export type GetLoginLogData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
    };
    url: '/v1/public/user/login_log';
};

export type GetLoginLogErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLoginLogError = GetLoginLogErrors[keyof GetLoginLogErrors];

export type GetLoginLogResponses = {
    /**
     * OK
     */
    200: GetLoginLogResponse;
};

export type GetLoginLogResponse2 = GetLoginLogResponses[keyof GetLoginLogResponses];

export type UpdateUserNotifyData = {
    body: UpdateUserNotifyRequest;
    path?: never;
    query?: never;
    url: '/v1/public/user/notify';
};

export type UpdateUserNotifyErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateUserNotifyError = UpdateUserNotifyErrors[keyof UpdateUserNotifyErrors];

export type UpdateUserNotifyResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UpdateUserNotifyResponse = UpdateUserNotifyResponses[keyof UpdateUserNotifyResponses];

export type GetOAuthMethodsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/public/user/oauth_methods';
};

export type GetOAuthMethodsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetOAuthMethodsError = GetOAuthMethodsErrors[keyof GetOAuthMethodsErrors];

export type GetOAuthMethodsResponses = {
    /**
     * OK
     */
    200: GetOAuthMethodsResponse;
};

export type GetOAuthMethodsResponse2 = GetOAuthMethodsResponses[keyof GetOAuthMethodsResponses];

export type UpdateUserPasswordData = {
    body: UpdateUserPasswordRequest;
    path?: never;
    query?: never;
    url: '/v1/public/user/password';
};

export type UpdateUserPasswordErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateUserPasswordError = UpdateUserPasswordErrors[keyof UpdateUserPasswordErrors];

export type UpdateUserPasswordResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UpdateUserPasswordResponse = UpdateUserPasswordResponses[keyof UpdateUserPasswordResponses];

export type UpdateUserRulesData = {
    body: UpdateUserRulesRequest;
    path?: never;
    query?: never;
    url: '/v1/public/user/rules';
};

export type UpdateUserRulesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateUserRulesError = UpdateUserRulesErrors[keyof UpdateUserRulesErrors];

export type UpdateUserRulesResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UpdateUserRulesResponse = UpdateUserRulesResponses[keyof UpdateUserRulesResponses];

export type QueryUserSubscribeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/public/user/subscribe';
};

export type QueryUserSubscribeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type QueryUserSubscribeError = QueryUserSubscribeErrors[keyof QueryUserSubscribeErrors];

export type QueryUserSubscribeResponses = {
    /**
     * OK
     */
    200: QueryUserSubscribeListResponse;
};

export type QueryUserSubscribeResponse = QueryUserSubscribeResponses[keyof QueryUserSubscribeResponses];

export type GetSubscribeLogData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
    };
    url: '/v1/public/user/subscribe_log';
};

export type GetSubscribeLogErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetSubscribeLogError = GetSubscribeLogErrors[keyof GetSubscribeLogErrors];

export type GetSubscribeLogResponses = {
    /**
     * OK
     */
    200: GetSubscribeLogResponse;
};

export type GetSubscribeLogResponse2 = GetSubscribeLogResponses[keyof GetSubscribeLogResponses];

export type UpdateUserSubscribeNoteData = {
    body: UpdateUserSubscribeNoteRequest;
    path?: never;
    query?: never;
    url: '/v1/public/user/subscribe_note';
};

export type UpdateUserSubscribeNoteErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateUserSubscribeNoteError = UpdateUserSubscribeNoteErrors[keyof UpdateUserSubscribeNoteErrors];

export type UpdateUserSubscribeNoteResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UpdateUserSubscribeNoteResponse = UpdateUserSubscribeNoteResponses[keyof UpdateUserSubscribeNoteResponses];

export type ResetUserSubscribeTokenData = {
    body: ResetUserSubscribeTokenRequest;
    path?: never;
    query?: never;
    url: '/v1/public/user/subscribe_token';
};

export type ResetUserSubscribeTokenErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ResetUserSubscribeTokenError = ResetUserSubscribeTokenErrors[keyof ResetUserSubscribeTokenErrors];

export type ResetUserSubscribeTokenResponses = {
    /**
     * No Content
     */
    204: void;
};

export type ResetUserSubscribeTokenResponse = ResetUserSubscribeTokenResponses[keyof ResetUserSubscribeTokenResponses];

export type UnbindDeviceData = {
    body: UnbindDeviceRequest;
    path?: never;
    query?: never;
    url: '/v1/public/user/unbind_device';
};

export type UnbindDeviceErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UnbindDeviceError = UnbindDeviceErrors[keyof UnbindDeviceErrors];

export type UnbindDeviceResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UnbindDeviceResponse = UnbindDeviceResponses[keyof UnbindDeviceResponses];

export type UnbindOAuthData = {
    body: UnbindOAuthRequest;
    path?: never;
    query?: never;
    url: '/v1/public/user/unbind_oauth';
};

export type UnbindOAuthErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UnbindOAuthError = UnbindOAuthErrors[keyof UnbindOAuthErrors];

export type UnbindOAuthResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UnbindOAuthResponse = UnbindOAuthResponses[keyof UnbindOAuthResponses];

export type UnbindTelegramData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/public/user/unbind_telegram';
};

export type UnbindTelegramErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UnbindTelegramError = UnbindTelegramErrors[keyof UnbindTelegramErrors];

export type UnbindTelegramResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UnbindTelegramResponse = UnbindTelegramResponses[keyof UnbindTelegramResponses];

export type UnsubscribeData = {
    body: UnsubscribeRequest;
    path?: never;
    query?: never;
    url: '/v1/public/user/unsubscribe';
};

export type UnsubscribeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UnsubscribeError = UnsubscribeErrors[keyof UnsubscribeErrors];

export type UnsubscribeResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UnsubscribeResponse = UnsubscribeResponses[keyof UnsubscribeResponses];

export type PreUnsubscribeData = {
    body: PreUnsubscribeRequest;
    path?: never;
    query?: never;
    url: '/v1/public/user/unsubscribe/pre';
};

export type PreUnsubscribeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PreUnsubscribeError = PreUnsubscribeErrors[keyof PreUnsubscribeErrors];

export type PreUnsubscribeResponses = {
    /**
     * OK
     */
    200: PreUnsubscribeResponse;
};

export type PreUnsubscribeResponse2 = PreUnsubscribeResponses[keyof PreUnsubscribeResponses];

export type VerifyEmailData = {
    body: VerifyEmailRequest;
    path?: never;
    query?: never;
    url: '/v1/public/user/verify_email';
};

export type VerifyEmailErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type VerifyEmailError = VerifyEmailErrors[keyof VerifyEmailErrors];

export type VerifyEmailResponses = {
    /**
     * No Content
     */
    204: void;
};

export type VerifyEmailResponse = VerifyEmailResponses[keyof VerifyEmailResponses];

export type QueryWithdrawalLogData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
    };
    url: '/v1/public/user/withdrawal_log';
};

export type QueryWithdrawalLogErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type QueryWithdrawalLogError = QueryWithdrawalLogErrors[keyof QueryWithdrawalLogErrors];

export type QueryWithdrawalLogResponses = {
    /**
     * OK
     */
    200: QueryWithdrawalLogListResponse;
};

export type QueryWithdrawalLogResponse = QueryWithdrawalLogResponses[keyof QueryWithdrawalLogResponses];
